spring:
  kafka:
    bootstrap-servers: localhost:9092

    security:
      protocol: PLAINTEXT

    properties:
      schema.registry.url: http://localhost:8081

    consumer:
      security:
        protocol: PLAINTEXT
      properties:
        specific.avro.reader: true

      auto-offset-reset: earliest
      group-id: demo-group-consumer

      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

    producer:
      client-id: demo-group-producer

      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

app:
  topic:  yourTopic
  consumer:
    group.id: consumerGroupId
